### PR TITLE
Small fixes

### LINKED ISSUE #31: Give user menu z-index
The user menu stacks behind other things in some instances, so just needs a z-index to keep it in front.

### PR DESCRIPTION
**Pull request by mariehooper**
This PR adds z-index to dropdown menu and updates display name to authors name.

Closes #31 , #32

### CODE REVIEW

File: src/components/SubmissionList.js [hunk 1]
```diff
@@ -80,10 +80,6 @@ export default function SubmissionList({ users, contributor, submissions }) {
 }
 
 SubmissionList.propTypes = {
-  contributor: PropTypes.shape({
-    displayName: PropTypes.string.isRequired,
-    photoURL: PropTypes.string.isRequired,
-  }).isRequired,
   users: PropTypes.object.isRequired,
```
Comment (pdhoopr) [inline src/components/SubmissionList.js]: We should go through and change these general propTypes to be more specific at some point, but probably in the initial refactor, not this branch.
